version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.6
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket pdomala-lambda-pipeline --output-template-file outputSamTemplate.yaml
  build:
    commands:
      - python --version
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml